### ISSUE TITLE
文章页向下滚动后，上方的导航栏消失，想返回首页比较麻烦

### ISSUE THREAD

**Issue by zgy0617** [guqing/halo-theme-higan#10]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/88391075/212447062-b0a0276f-a061-4ba4-a3c9-a5dde282cbef.png">
文章向下滚动后再回到上面，导航栏就不见了。
<img width="346" alt="image" src="https://user-images.githubusercontent.com/88391075/212447082-9cfb3c07-0587-451c-b76b-1b91b8206860.png">

**Comment by guqing** [comment]
文章向下滚动后会，菜单 icon 的功能会切换为是否展示目录，所以隐藏了顶部菜单，因为是共用一个 menu icon，因此不好处理，但确实返回首页不方便除非滚动到底部，我会考虑在滚动到顶部时惦记 menu icon 同时切换顶部菜单和目录的隐藏和显示。
如果是在内容部分则只切换目录的隐藏和显示。

**Comment by guqing** [comment]
已在 2.2.0 版本优化 https://github.com/guqing/halo-theme-higan/releases/tag/v2.2.0
