### ISSUE TITLE
导航栏文字前出现意料之外的空格

### ISSUE THREAD

**Issue by HowieHz** [guqing/halo-theme-higan#113]
```html
<li>
</li>
<li>
</li>
```
两个这样的 li 标签中间就会出现空格

首页
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/6866352b-4ea6-4ece-8e09-e8b278ff4ad2)

文章页
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/73ee0910-91dd-4130-ba01-48272e6130b6)

页脚
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/ecfde439-593c-4505-b340-49c95944cef0)

**Comment by guqing** [comment]
看起来并没有空格
<img width="571" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/0faaacb4-bc4b-4dd4-bc81-3604c2c9c690">
只是最后一个搜索那里会多处这么一个区域，貌似没有没有足够的理由说明这是因为你说的原因导致会出现空格

**Comment by HowieHz** [comment]
> 看起来并没有空格 <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/38999863/338407274-0faaacb4-bc4b-4dd4-bc81-3604c2c9c690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzMxMDMsIm5iZiI6MTcxODA3MjgwMywicGF0aCI6Ii8zODk5OTg2My8zMzg0MDcyNzQtMGZhYWFjYjQtYmM0Yi00ZGQ0LWJjODEtMzYwNGMyYzljNjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmN2UwOTExNTk2YzViYWIyMDhiOTAzNmM3MjhmNzNkZjhlN2M1M2JkYTEwZTBkZDZlM2FkZTBjYzNkYTM0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ApZYebhScxIqOUKM2MnvK9Yh117tnJQACly3lheYp4c"> 只是最后一个搜索那里会多处这么一个区域，貌似没有没有足够的理由说明这是因为你说的原因导致会出现空格

请对比
```html
<li>
</li>
<li>
</li>
```
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/1c47684e-14d7-4c78-bf32-0d1d6c4c450b)

```html
<li>
</li><li>
</li>
```
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/aa3a21f2-e549-41f5-a6dc-620032d1a353)

对于这个问题可能的搜索引擎关键字 `浏览器渲染行内换行符` `li 标签行内有空格`

**Comment by HowieHz** [comment]
补充
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/4da997c6-9f7d-4721-84fe-f78d36169006)
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/48d9b751-9e3e-4dc6-9813-1e6357a26b2f)

另外我这样选取文字是按住`alt`然后鼠标左键拖动选取

**Comment by HowieHz** [comment]
首页和页底的用display: flex 也行，文章导航栏的只能display: inline-table，display: inline-flex 会让文字轻微上移

**Comment by HowieHz** [comment]
@THYUU 说这种span里套ul li的写法很老了，所以也要找老的方法去解决这个，也就是 display: inline-table。
为了一致性所以三个位置都用 display: inline-table 修改。

**Comment by guqing** [comment]
> @THYUU 说这种span里套ul li的写法很老了，所以也要找老的方法去解决这个，也就是 display: inline-table。 为了一致性所以三个位置都用 display: inline-table 修改。

这个主题是迁移的所以没有过多的去修改原来的 html 结构，如果没有什么实质性的影响我不建议去处理这个，可能会造成其他未知的问题

**Comment by HowieHz** [comment]
> > @THYUU 说这种span里套ul li的写法很老了，所以也要找老的方法去解决这个，也就是 display: inline-table。 为了一致性所以三个位置都用 display: inline-table 修改。
> 
> 这个主题是迁移的所以没有过多的去修改原来的 html 结构，如果没有什么实质性的影响我不建议去处理这个，可能会造成其他未知的问题

好的，我给原主题也提了 issue，不知道作者会做何处理 [probberechts/hexo-theme-cactus#388](https://github.com/probberechts/hexo-theme-cactus/issues/388)。
加 display: inline-table 是在不更改 html 结构，仅通过 css 解决的最佳方案。

**Comment by HowieHz** [comment]
> > @THYUU 说这种span里套ul li的写法很老了，所以也要找老的方法去解决这个，也就是 display: inline-table。 为了一致性所以三个位置都用 display: inline-table 修改。
> 
> 这个主题是迁移的所以没有过多的去修改原来的 html 结构，如果没有什么实质性的影响我不建议去处理这个，可能会造成其他未知的问题

![image](https://github.com/guqing/halo-theme-higan/assets/94725606/2585c92a-0352-4ce7-9551-cced5b704cc7)
https://github.com/probberechts/hexo-theme-cactus/commit/a15f8ace0f9a144ea8356c7c38d11f2f85652ea5
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/1b16a329-1c64-4f1d-ae45-29d59fe32b30)
上游的 issue 被回复了，大概是已经被修复了，是将

```html
<li>
</li>
<li>
</li>
```

转换为

```html
<li>
</li><li>
</li>
```

办法来修复这个问题？

**Comment by guqing** [comment]
> 上游的 issue 被回复了，大概是已经被修复了，是将
> 转换为
> 
> ```
> <li>
> </li><li>
> </li>
> ```
> 
> 办法来修复这个问题？不是很懂 ejs。

他是通过使用注释来去除 html 结构中的 li 之前的空格来实现的,如果你在意可以修改一下，目前我不打算解决，除非是直接重构整个 html 结构

**Comment by HowieHz** [comment]
> > 上游的 issue 被回复了，大概是已经被修复了，是将
> > 转换为
> > ```
> > <li>
> > </li><li>
> > </li>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 办法来修复这个问题？不是很懂 ejs。
> 
> 他是通过使用注释来去除 html 结构中的 li 之间的空格来实现的,如果你在意可以自行修改一下，目前我不打算解决，除非是直接重构整个 html 结构

感谢你的回复❤️
