### ISSUE TITLE
求教，.bg-base-100 .bg-base-200 如何正确运行？

### ISSUE THREAD

**Issue by HowieHz** [guqing/halo-theme-higan#115]
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/1fc76bb6-24e2-40e7-9c95-c1a4fd590687)
我看到 main.css 中有两个样式
.bg-base-100 {} 
.bg-base-200 {} 

共同的特点是都有被使用，但是里面的变量 --b2 --fallback-b2 --b1 --fallback-b1 在项目中是找不到的。
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/6d8b219d-735a-4b9a-9097-563f05c8da1c)
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/93811509-b2d0-4521-9648-996b01818ade)

通过检索发现这个可能是出自 daisyUI？

我想请教下作者大大这四个变量在项目中被定义在了哪，还是说这其实是被弃用的样式？😵

**Comment by guqing** [comment]
> 我想请教下作者大大这四个变量在项目中被定义在了哪，还是说这其实是被弃用的样式？😵

tailwindcss 拷贝过来的定义，它用在瞬间的视频卡片上，实际上这个 bg-base-200 和 bg-base-100 可以直接删掉，效果是这样的
<img width="758" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/d9d8eb76-d5a8-4697-8cc4-998e4856b021">

如果你需要 b2
```
    --b1: 100% 0 0;
    --b2: 96.1151% 0 0;
```

**Comment by HowieHz** [comment]
> > 我想请教下作者大大这四个变量在项目中被定义在了哪，还是说这其实是被弃用的样式？😵
> 
> tailwindcss 拷贝过来的定义，它用在瞬间的视频卡片上，实际上这个 bg-base-200 和 bg-base-100 可以直接删掉，效果是这样的 <img alt="image" width="758" src="https://private-user-images.githubusercontent.com/38999863/338427317-d9d8eb76-d5a8-4697-8cc4-998e4856b021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODAwMDMsIm5iZiI6MTcxODA3OTcwMywicGF0aCI6Ii8zODk5OTg2My8zMzg0MjczMTctZDlkOGViNzYtZDVhOC00Njk3LThjYzQtOTk4ZTQ4NTZiMDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA0MjE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOGMyYzdkYzdlMjEwZjFkZDIwZjRkODA5OTlmY2I1ZDQ0MTQwMzY0YWFmMDUzMjRjODI2YjE0M2JhM2Q4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YmClsoGFKQHmf4bf3Z7GD0tVPoWoU1ijRZfGR5hEue0">
> 
> 如果你需要 b2
> 
> ```
>     --b1: 100% 0 0;
>     --b2: 96.1151% 0 0;
> ```

感谢解答❤️
