### ISSUE TITLE
2.9.0版本，头像无法正常显示

### ISSUE THREAD

**Issue by ViicesCai** [guqing/halo-theme-higan#119]
![Snipaste_2024-12-30_18-01-43](https://github.com/user-attachments/assets/f1af02f8-534c-43a2-95aa-a7bee4111634)
使用2.9.0时，版本号仍然显示2.8.0，同时网站的头像不显示了。

**Comment by guqing** [comment]
是否有使用了页面缓存插件，建议清理一下页面缓存，我没有遇到这个问题

**Comment by ViicesCai** [comment]
原本是正常的，今天从2.4.0更新到最新版就发现问题了。blog：https://pisay.life

**Comment by ViicesCai** [comment]
去除 background-image：url 中的前缀，是可以正常展示的。
![图片](https://github.com/user-attachments/assets/3e12e74c-cf62-4686-8ba2-175d7d7694aa)

**Comment by guqing** [comment]
升级一下你 Halo 的版本号目前 Halo 最新版是 2.20.12

**Comment by guqing** [comment]
关于你提到的 version 在 2.9 还是显示 2.8 的问题确实存在，应该是发版本时忘记改版本号了，回头我配置一下 CI

**Comment by guqing** [comment]
稍后重新发布一个版本并移除掉站点 logo 使用缩略图的前缀

**Comment by ViicesCai** [comment]
感谢解答！该版本要配合高版本的 halo 使用吗？我当前halo的版本是2.6.0

**Comment by guqing** [comment]
已经发布版本了，建议更新一下

**Comment by guqing** [comment]
> 感谢解答！该版本要配合高版本的 halo 使用吗？我当前halo的版本是2.6.0

最好是升级到 Halo 最新版使用，2.6 版本太低了性能很差，后续的 Halo 做了很多性能优化和新特性比如缩略图机制就很实用

**Comment by guqing** [comment]
由于问题已经修复我将关闭此 issue ，如没有得到解决请随时打开
