### ISSUE TITLE
当菜单多于6个的时候 会出现滚动条遮挡文字的情况

### ISSUE THREAD

**Issue by fireinrain** [guqing/halo-theme-higan#12]
非常感谢大大开发的这个主题 表示很喜欢，但是使用的时候发现一个问题，如题,情况如下图:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/14249262/216662616-c94b1090-081d-4c67-a2c9-6441af76c1e7.png">
时候可以把这个滚动条往右边移动一些, 当菜单少的时候不会出现这种情况。

**Comment by guqing** [comment]
感谢你对此提出 issue ，我已去掉了 toc 的滚动条显示，且不会影响 toc 过长时的滚动
已修复 #13
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/38999863/219328182-81a43090-2ac5-469a-a8a1-da091894b7a3.png">

**Comment by guqing** [comment]
近期会尽快发一个版本，如有问题随时 reopen 此 PR，我先将其关闭
