### ISSUE TITLE
文章目录无法跳转

### ISSUE THREAD

**Issue by z0sen** [guqing/halo-theme-higan#14]
使用 markdown 编辑器插件 [plugin-bytemd](https://github.com/halo-sigs/plugin-bytemd) 编写markdown 文档，发布之后点击右侧目录无法跳转位置，但默认编辑器可以，这个是主题问题？还是插件问题？还是 halo2 的问题？

**Comment by z0sen** [comment]
> 使用 markdown 编辑器插件 [plugin-bytemd](https://github.com/halo-sigs/plugin-bytemd) 编写markdown 文档，发布之后点击右侧目录无法跳转位置，但默认编辑器可以，这个是主题问题？还是插件问题？还是 halo2 的问题？

更换其他主题后点击可跳转，在 higan 主题下，英文可跳转定位，中文标题无法跳转

**Comment by guqing** [comment]
感谢反馈 我会尝试浮现一下

**Comment by guqing** [comment]
经尝试已复现，中文标题无法跳转但是英文可以，这是 tocbot 的 bug，他们已经修复了但是一直没有发布版本，我将使用 github 上最新的产物来修复此问题 https://github.com/tscanlin/tocbot/commit/2ff281d77cd2fe2c8a33579fc8c496df2a22a777

**Comment by guqing** [comment]
已修复：https://github.com/guqing/halo-theme-higan/commit/23fb919f5f047a859be20a86e08745ece866e729
