### ISSUE TITLE
请问首页个人简介怎么设置

### ISSUE THREAD

**Issue by Uyouii** [guqing/halo-theme-higan#15]
没有在主题设置里发现个人简介的填写栏。

另外可以给首页和文章页添加类似于关于页面的背景图片选项吗。

**Comment by guqing** [comment]
> 没有在主题设置里发现个人简介的填写栏。
> 
> 
> 
> 另外可以给首页和文章页添加类似于关于页面的背景图片选项吗。

首页的说明是填在系统设置的站点描述里面的，后续考虑单独在主题设置里出一个单独的，关于页面的图片是用页面功能和markdown写html得到的

**Comment by guqing** [comment]
后续我会优化一下样式，尽量加一些图片展示的方式

**Comment by Uyouii** [comment]
> 后续我会优化一下样式，尽量加一些图片展示的方式

期待
