### ISSUE TITLE
请问归档页面如何显示

### ISSUE THREAD

**Issue by Uyouii** [guqing/halo-theme-higan#16]
发现博主的网站可以显示归档页面，https://guqing.xyz/archives 
试了下同样的 path 会显示 NotFound
<img width="637" alt="截屏2023-03-03 16 41 54" src="https://user-images.githubusercontent.com/25459212/222673185-57c6378b-3961-492b-bb21-1ef7e18ae8e4.png">

**Comment by guqing** [comment]
> 发现博主的网站可以显示归档页面，https://guqing.xyz/archives 
> 
> 试了下同样的 path 会显示 NotFound
> 
> <img width="637" alt="截屏2023-03-03 16 41 54" src="https://user-images.githubusercontent.com/25459212/222673185-57c6378b-3961-492b-bb21-1ef7e18ae8e4.png">
> 
> 

主题是哪个版本呢 你试试2.2.0 https://github.com/guqing/halo-theme-higan/releases

**Comment by Uyouii** [comment]
怀疑是不是后端的bug，因为用默认主题也无法显示。
higan版本是2.2.0， halo版本是2.3.0

主题路由设置：
<img width="796" alt="截屏2023-03-03 23 29 06" src="https://user-images.githubusercontent.com/25459212/222760235-3c3402fc-28ba-4660-97b7-35404b8a1352.png">

归档页面显示：
<img width="946" alt="截屏2023-03-03 23 29 36" src="https://user-images.githubusercontent.com/25459212/222760322-71a3af17-23fd-43e1-a07d-34c1b61f8b09.png">

**Comment by guqing** [comment]
> 怀疑是不是后端的bug，因为用默认主题也无法显示。 higan版本是2.2.0， halo版本是2.3.0
> 
> 主题路由设置： <img alt="截屏2023-03-03 23 29 06" width="796" src="https://user-images.githubusercontent.com/25459212/222760235-3c3402fc-28ba-4660-97b7-35404b8a1352.png">
> 
> 归档页面显示： <img alt="截屏2023-03-03 23 29 36" width="946" src="https://user-images.githubusercontent.com/25459212/222760322-71a3af17-23fd-43e1-a07d-34c1b61f8b09.png">

你的网站归档页我试了一下是可以访问的，https://uyouii.cool/archives
需要注意的是结尾不能加斜杠否则访问不了

**Comment by Uyouii** [comment]
确实添加了"/"无法访问，暂时没找到原因为什么chrome 浏览器会自动补全archives 末尾的斜杠，把文章前缀改为post了，感谢博主答疑。

**Comment by guqing** [comment]
我看你的博客有些文章的 toc 点击不能跳转比如 https://uyouii.cool/posts/deng-xiao-ping-shi-dai，原因是 bytemd 编辑器1.1.0版本之前的版本渲染标题时没有在 h 标签上面加 id，可以使用 1.1.0 版本 bytemd 重新发布一下那些不能跳转的文章

**Comment by Uyouii** [comment]
> 我看你的博客有些文章的 toc 点击不能跳转比如 https://uyouii.cool/posts/deng-xiao-ping-shi-dai ，原因是 bytemd 编辑器1.1.0版本之前的版本渲染标题时没有在 h 标签上面加 id，可以使用 1.1.0 版本 bytemd 重新发布一下那些不能跳转的文章

原来是这个原因，感谢答复🙏
