### ISSUE TITLE
具体的标签和分类项无法翻页

### ISSUE THREAD

**Issue by Uyouii** [guqing/halo-theme-higan#17]
主页有分页的按钮，但是具体的标签和分类下的列表则不会显示翻页按钮。
halo版本2.3.0，higan版本2.2.0

**Comment by guqing** [comment]
新版本已发布到应用市场可以升级使用 https://www.halo.run/store/apps/app-eiTyL?tab=releases， 我将关闭此 issue 如还有问题欢迎随时打开♥️
