### ISSUE TITLE
首页个人简介无法换行

### ISSUE THREAD

**Issue by heyzqq** [guqing/halo-theme-higan#25]
首页个人简介的内容无法换行，无法分段，希望可以支持一下。

要是能支持 Markdown 那就更好了 ^.^

**Comment by guqing** [comment]
支持写 html ，如果需要换行可以 使用 br 或者 p 标签

**Comment by heyzqq** [comment]
> 支持写 html ，如果需要换行可以 使用 br 或者 p 标签

噢噢，好的哈~

**Comment by guqing** [comment]
我将关闭此 issue 如果还有问题欢迎随时打开
