### ISSUE TITLE
瞬间页面图片展示原始大小，评论默认打开

### ISSUE THREAD

**Issue by LiumxRyan** [guqing/halo-theme-higan#26]
瞬间页面图片现在展示的原始大小，可以展示缩略图吗
瞬间页面的评论区默认是打开状态，可以默认设置为收起状态吗

**Comment by guqing** [comment]
瞬间的样式你使用的最新版本主题试试 https://guqing.xyz/moments

**Comment by guqing** [comment]
缩略图这个应该需要瞬间插件来支持，目前没有瞬间没有提供缩略图主题无法去处理

**Comment by guqing** [comment]
由于此 issue 长期没有回复，我将关闭此 issue，如还存在问题可以重新打开
