### ISSUE TITLE
社交资料是否可以加入一些常见的写作平台，比如公众号等？

### ISSUE THREAD

**Issue by heyzqq** [guqing/halo-theme-higan#27]
虽然公众号严格来说不算社交方式，但是很多写博客的人，一般会通过公众号等平台，去和读者交流，不知道是否能加到社交资料中？

或者，提供其他的展示方式也好~

**Comment by guqing** [comment]
公众号这种可以考虑在你的 About 页面内放一个二维码，首页展示的社交账号需要点击链接能直接跳转的更好一些

**Comment by heyzqq** [comment]
> 公众号这种可以考虑在你的 About 页面内放一个二维码，首页展示的社交账号需要点击链接能直接跳转的更好一些，比如下面的这个博客： https://www.manction.com/s/about

好的，谢谢~

**Comment by guqing** [comment]
我将关闭此 issue 如还有问题欢迎随时打开
