### ISSUE TITLE
是否存在作者页

### ISSUE THREAD

**Issue by jdysya** [guqing/halo-theme-higan#32]
<img width="1046" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/73117213/95dca021-77f0-4a89-89a8-7b945a242d18">
例如访问https://guqing.xyz/authors/guqing，会显示错误，主题并没有适配`/authors`页面

**Comment by guqing** [comment]
目前确实没有作者页模板，我会添加一个🎉
