### ISSUE TITLE
瞬间（moments）页面无法显示大图

### ISSUE THREAD

**Issue by jdysya** [guqing/halo-theme-higan#33]
使用那个可以放大内容区图片的插件，没有生效，不知道是不是我配置的有问题（我配置的选择器是`.content`）

**Comment by guqing** [comment]
Hi @jdysya ，请尝试 配置为 `article .content`  试试，

**Comment by jdysya** [comment]
> Hi @jdysya ，请尝试 配置为 `article .content` 试试，

好像还是没有效果，文章详情页倒是没问题，就这个moment页面，试了好几个选择器都没效果

**Comment by guqing** [comment]
> > Hi @jdysya ，请尝试 配置为 `article .content` 试试，
> 
> 好像还是没有效果，文章详情页倒是没问题，就这个moments页面，试了好几个选择器都没效果

目前这个插件貌似只能配置一个选择器，所以可能这个插件后续得改进一下，最好是能支持路由匹配的方式来配置选择器，比如 /moments/** 的 选择器为 `. medium`, /archives/** 的选择器为 `.content` 之类，晚点我优化一下 moment 页面的 class 属性让其和文章详情统一来临时解决这个问题。

**Comment by guqing** [comment]
看了一下是 plugin-lightgallery 插件的问题，它只支持文章和自定义页面的图片放大。

已向 [plugin-lightgallery](https://github.com/halo-sigs/plugin-lightgallery) 插件发起 PR https://github.com/halo-sigs/plugin-lightgallery/pull/6 ，合并后此问题将得到解决，等待 plugin-lightgallery 发布新版本即可。

**Comment by guqing** [comment]
PR https://github.com/halo-sigs/plugin-lightgallery/pull/6 已被合并，我将关闭此 issue
