### ISSUE TITLE
请问 guqing.xyz/links 的友链的效果是怎么实现的，是主题支持的吗？

### ISSUE THREAD

**Issue by heyzqq** [guqing/halo-theme-higan#41]
也想要实现这样的效果：https://guqing.xyz/links。
但是不知道如何实现，【页面】只能写 markdown 和普通文档格式的，不知道如何实现。

![image](https://github.com/guqing/halo-theme-higan/assets/47818994/17e19913-61a7-4586-97ed-a63e9bb11717)

请问大佬是怎么实现的呀？

**Comment by guqing** [comment]
安装友链插件 https://halo.run/store/apps/app-hfbQg

**Comment by heyzqq** [comment]
我以为是主题支持的，安装后可以了，感谢~
