### ISSUE TITLE
再有目录的文章中出现了一跟竖线丨

### ISSUE THREAD

**Issue by libashanxi** [guqing/halo-theme-higan#42]
如图这样
![image](https://github.com/guqing/halo-theme-higan/assets/65264574/e6ab38e6-15f4-4ea8-a109-a632bdf07aad)
但是我看相同主题别人的即使有图片也没有这个横线，我不知道是不是我哪里做了什么设置有影响吗？特来求助提问

**Comment by libashanxi** [comment]
刚才继续试了一下，好像不是有图片的文章出现竖线，是有目录的文章会有这个竖线，这个竖线是和上面的首页位置保持一致的，如果我的菜单够多，这个竖线会挡住文章中的内容
![image](https://github.com/guqing/halo-theme-higan/assets/65264574/3fda622e-8012-40be-b064-b7d897bd3e7f)

**Comment by guqing** [comment]
使用的什么版本呢

**Comment by libashanxi** [comment]
一开始用的2.4的正式版本，我以为是我版本问题，我又从github上下载了main版本，升级了一下
现在应该还是2.4版本
![image](https://github.com/guqing/halo-theme-higan/assets/65264574/81db4d25-4342-442d-9cb4-adb7b1db851e)

**Comment by guqing** [comment]
提供一下你的博客地址 我看看

**Comment by libashanxi** [comment]
https://halo.libashanxi.xyz:8443/2023/1690431850730

**Comment by guqing** [comment]
这个样式的来源是一个叫 tocbot.css 的样式文件
<img width="1241" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/ae320697-d8fd-4043-a3d7-1949f0ed7f92">
但是主题中目前没有这个 tocbot.css
<img width="610" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/7123db47-b8fb-4fa9-866f-b74c83e9259f">
你看看有没有在全局代码注入等地方引入过，跟这一段代码有关
<img width="1017" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/96c868c8-6f0f-4aef-8320-61bf7f820be5">

**Comment by libashanxi** [comment]
okok，那我把这个插件关掉吧，谢谢大佬
