### ISSUE TITLE
无法使用katex数学公式

### ISSUE THREAD

**Issue by L4v3nder** [guqing/halo-theme-higan#43]
Halo version:2.7.0
非常喜欢这款主题，侍奉的简洁，谢谢作者。
但是我在使用的时候发现katex数学公式无法被解析，装了halo的katex插件也无法使用，希望作者大大能修复一下

**Comment by guqing** [comment]
我试了一下没有发现不能用呢，可以提供一下可以复现的公式或步骤吗
<img width="850" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/5ff740e7-b33d-4927-88de-a50ca436b208">

**Comment by L4v3nder** [comment]
![image](https://github.com/guqing/halo-theme-higan/assets/90501040/80cda2a0-810b-4342-b6bb-859bfaa12a34)
![image](https://github.com/guqing/halo-theme-higan/assets/90501040/624b420c-0ece-4839-9436-3b5f037cb45b)
像这样就无法使用，在编辑器中可以显示，但在文章就无法解析，还有在单$时无法使用

**Comment by guqing** [comment]
你试试默认主题呢，这可能与主题没有关系和插件有关,写法是双$符号然后回车
<img width="349" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/a1ea12f5-60ba-43cf-bf13-1901b697a6f3">

**Comment by L4v3nder** [comment]
好吧看起来确实是插件的问题，Katex的插件无法使用
