### ISSUE TITLE
希望优化的地方

### ISSUE THREAD

**Issue by L4v3nder** [guqing/halo-theme-higan#44]
![image](https://github.com/guqing/halo-theme-higan/assets/90501040/0b478b06-4b2a-4044-b581-e9d002ca7fc1)
文章侧面的侧边栏目录在多级目录多了以后出现滑块与主体十分的突兀，希望作者能把多级目录一开始只显示最高一级的选择之后再展开(像是[这个样](https://lixingyong.com/2021/01/05/halo%E4%B8%BB%E9%A2%98sakura%E9%A3%9F%E7%94%A8%E8%AF%B4%E6%98%8E#toc-head-8)的)或者说能把这个滑块美化隐藏

**Comment by guqing** [comment]
很好的建议👍

**Comment by L4v3nder** [comment]
2.5版本没有优化这个地方(ㄒoㄒ)

**Comment by guqing** [comment]
2.5是之前忘记发版本的功能，有人说moment tag出不来所以发了一下，还没修，一直忙于 halo-dev 搞忘了🫣明晚修复🫨

**Comment by guqing** [comment]
已通过以下两个提交修复此问题：
- https://github.com/guqing/halo-theme-higan/pull/48
- https://github.com/guqing/halo-theme-higan/commit/ed4d7c13589be5bace02b0b6059cfb842422b078

可以先下载 main 分支安装使用

**Comment by L4v3nder** [comment]
![image](https://github.com/guqing/halo-theme-higan/assets/90501040/36022114-fdcb-45f7-ad8e-0a68e8e689c6)
貌似没有变化，我是把原来的主题删除然后在这里
![image](https://github.com/guqing/halo-theme-higan/assets/90501040/cfb39514-a62d-495f-b76e-d6a5af626bca)
下载主题安装

**Comment by guqing** [comment]
>  貌似没有变化，我是把原来的主题删除然后在这里
这是因为没有发版 main 分支的版本号还是原来的版本号，所以浏览器缓存还在，https://www.halo.run/store/apps/app-eiTyL?tab=releases 已经发布了，你可以重新从应用市场更新试试，我刚刚试了我的是可以的

**Comment by L4v3nder** [comment]
可以了  辛苦啦
