### ISSUE TITLE
希望能支持自定义 highlight 的主题

### ISSUE THREAD

**Issue by ViicesCai** [guqing/halo-theme-higan#45]
![图片](https://github.com/guqing/halo-theme-higan/assets/31115208/b62c1611-e254-4d67-a71d-1a2cb2187892)
在深色模式下，这个代码高亮的主题太突兀了。

**Comment by guqing** [comment]
可以自定义的吧
<img width="866" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/8ba03c15-95c9-44af-b352-c1999c48c753">
你说有没有可能要去代码高亮的插件里面设置
<img width="791" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/b7b28cdc-2134-47fb-a37c-dd9368618b7b">

**Comment by ViicesCai** [comment]
感谢您的回复！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年8月4日 10:44
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [guqing/halo-theme-higan] 希望能支持自定义 highlight 的主题 (Issue #45)


可以自定义的吧
[image]<https://user-images.githubusercontent.com/38999863/258281678-8ba03c15-95c9-44af-b352-c1999c48c753.png>
你说有没有可能要去代码高亮的插件里面设置
[image]<https://user-images.githubusercontent.com/38999863/258281754-b7b28cdc-2134-47fb-a37c-dd9368618b7b.png>

―

**Comment by guqing** [comment]
若已解决我将关闭此 issue 有问题随时 reopen
