### ISSUE TITLE
Releases 2.4.0 templete目录下的css文件异常

### ISSUE THREAD

**Issue by Dyzmj** [guqing/halo-theme-higan#46]
Releases 2.4.0中的 /templates/assets/dist/style.css 文件并非 2.4.0版本，里面缺少 ".moment .tag"元素下的样式，导致瞬间页面中 tag 标签无法显示，我看你的网站里直接引用的是 “"https://guqing.xyz/themes/guqing-higan/assets/dist/style.css?v=2.4.0"，我把这个css文件复制过去，标签就正常显示了

**Comment by guqing** [comment]
先用 main 分支下载最新的,我近期会发个版本, 你不说我都忘记了这个事儿😅 https://github.com/guqing/halo-theme-higan/archive/refs/heads/main.zip

**Comment by guqing** [comment]
已发布 2.5.0 升级后尝试，https://www.halo.run/store/apps/app-eiTyL?tab=releases
