### ISSUE TITLE
请问单篇文章的横向距离太窄，可以修改哪个源码配置就能改宽一点不？

### ISSUE THREAD

**Issue by yankooo** [guqing/halo-theme-higan#47]
<img width="1785" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/31951382/df5dcc25-6706-47b1-930c-21f3e2199119">

比如这个例子。
1，文章间距太小了，导致不断换行，代码块也只能看见一部分，需要拖动代码框里的滑块才可以看完整代码。

**Comment by guqing** [comment]
后续我为内容区域宽度增加一个媒体查询以确保可以在宽屏分辨率下将宽度变大

**Comment by guqing** [comment]
我刚刚尝试了一下，如果改了宽度会导致布局重心往左边偏移使主题的整体风格变得很拉，你可以在 halo 的系统设置的内容页面代码注入中加入以下代码试试
```
@media (min-width: 1280px) {
  .max-width {
    max-width: 56rem;
  }
}

@media (min-width: 1536px) {
  .max-width {
    max-width: 64rem;
  }
}
```

**Comment by yankooo** [comment]
<img width="1507" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/31951382/88bc718a-8023-4918-a08b-d5222b61f505">好像不行，没生效😰

**Comment by guqing** [comment]
> 好像不行，没生效😰

这样写，使用 style 标签包裹起来
```html
<style>
@media (min-width: 1280px) {
  .max-width {
    max-width: 56rem;
  }
}

@media (min-width: 1536px) {
  .max-width {
    max-width: 64rem;
  }
}
</style>
```

<img width="609" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/6df465c3-8265-456d-889f-da188d83c5c5">

**Comment by yankooo** [comment]
大佬👍
