### ISSUE TITLE
【问题】如何修改字号大小？

### ISSUE THREAD

**Issue by heihei180** [guqing/halo-theme-higan#49]
首先感谢开发者提供的主题，很不错。谢谢~~！！！

作为女生可能喜欢小点的字，狠可爱，但是我想要大字啊，太费眼了~~哈哈
想问一下字体如何调节呢？现在是否支持调教字体大小？感觉整体有点小啊

**Comment by guqing** [comment]
主题设置里面有个字体大小设置，默认是小号字体，你可以改个大号

<img width="879" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/1e0e3380-ec39-4b3f-8f38-82d787050d59">
