### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by github-ayio** [guqing/halo-theme-higan#50]
作者您好，感谢贡献这么优秀的主题。
向您反馈个问题，但与此模板无关：
就是在启用highlight这个插件之后，只要是亮色的highlight主题，包裹的容器四周出现“虚边”的情况，很影响视觉感受。希望halo官方能处理下呢。
![Snipaste_2023-11-30_10-09-01](https://github.com/guqing/halo-theme-higan/assets/23180747/4ec1e52e-f92c-417d-9ea4-10d1f101c993)

**Comment by guqing** [comment]
感谢反馈，确实有此问题😆，像素眼👍

**Comment by github-ayio** [comment]
此外，借小姐姐的地方再反馈个halo我觉得是挺严重的bug：
应用halo2.10默认主题，后台菜单删除之后，前台打开空白，且不知道如何恢复😓
![Snipaste_2023-11-30_14-37-37](https://github.com/guqing/halo-theme-higan/assets/23180747/ee4c277c-c883-45ac-81d7-f7efba02e65e)

**Comment by guqing** [comment]
> 此外，借小姐姐的地方再反馈个halo我觉得是挺严重的bug： 应用halo2.10默认主题，后台菜单删除之后，前台打开空白，且不知道如何恢复😓 

不是这个主题的问题到 halo-dev/hao 下提，这里不会处理 halo 的问题，而且提到 halo 仓库下有助于让社区都能看到和讨论
