### ISSUE TITLE
进入文章内容页之后无法快捷回到首页

### ISSUE THREAD

**Issue by github-ayio** [guqing/halo-theme-higan#51]
美女，我觉得有个缺憾就是无法从文章页直接回到首页，每次只能手动更改浏览器地址，总感觉没有闭环。是否考虑后续新增快捷回到首页功能呢，例如可以考虑在这里增加？
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/2c63a4d2-7d34-4059-b3cf-759a341528db)

**Comment by guqing** [comment]
貌似默认是有首页这个菜单项的所以就没有添加其他入口了
<img width="986" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/e811b760-a690-4230-ba5a-0245adb02a4d">

**Comment by github-ayio** [comment]
@guqing 所以这个和我给halo提的问题是一样的，用户是可以删除所有菜单的，halo并没有针对删除主菜单做限制，这是很操蛋的行为，我的话是不设置任何菜单的，且以后应该也不会设置，所以，我没有退路(lll￢ω￢)
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/fd4088ad-534c-42c1-b2c5-9035d51f2923)

**Comment by guqing** [comment]
那后续我在以下这个区域添加一个入口用于回到首页，其他地方也确实没有合适的位置能添加了🤣
<img width="324" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/b2022277-02bf-45ec-a242-95a7aeb47193">

**Comment by github-ayio** [comment]
非常感谢！
其实，最开始，我以为这款主题就是这么故意设计的，甚至感叹他的极致的极简作风，所以强迫自己去尝试并理解，然而最终...没忍住😓😄
@guqing

**Comment by guqing** [comment]
> 非常感谢！ 其实，最开始，我以为这款主题就是这么故意设计的，甚至感叹他的极致的极简作风，所以强迫自己去尝试并理解，然而最终...没忍住

哈哈，原主题确实是这么设计的，我也是移植过来的，因为极简所以有些东西就不好添加，不过你提的这一点确实有待改进不然对于没有首页菜单的用户返回首页确实麻烦

**Comment by github-ayio** [comment]
突然想到，可以判断是否设置菜单项，如果没有设置菜单项，文章页才显示回到首页的icon。这样的话，就不改变原有的设计了~

**Comment by guqing** [comment]
新版本已发布到应用市场可以升级使用 https://www.halo.run/store/apps/app-eiTyL?tab=releases， 我将关闭此 issue 如还有问题欢迎随时打开♥️
