### ISSUE TITLE
主题更新之后貌似字体变了

### ISSUE THREAD

**Issue by github-ayio** [guqing/halo-theme-higan#57]
主题更新之后highlight字体变了，没以前圆润了，现在骨瘦如柴~

![image](https://github.com/guqing/halo-theme-higan/assets/23180747/0ce16403-af5e-46e9-ae2f-8b2162eb5508)

**Comment by guqing** [comment]
我这里看是正常的，貌似没有改过字体，使用的什么浏览器呢，会不会是因为浏览器不同导致效果不一样，同样的字体我刚刚用 safari 就和 chrome 很大差异

**Comment by github-ayio** [comment]
我丢~ highlight插件字体变了？？？
![企业微信截图_17023740422834](https://github.com/guqing/halo-theme-higan/assets/23180747/fdc7c28b-978b-4bd2-9ba1-3e96c68fbe3a)

**Comment by guqing** [comment]
感谢反馈，我将提交 PR 来覆盖 code 的字体♥️
