### ISSUE TITLE
关于圆形头像ui的建议

### ISSUE THREAD

**Issue by jiancaiZhong** [guqing/halo-theme-higan#59]
我对比了两种头像，圆的和方的。

![1702373148031](https://github.com/guqing/halo-theme-higan/assets/110711363/3551bcd3-43ec-4abb-b1b4-621746483131)

有点强迫症，有点小建议：希望能去除圆形头像的描边，有个 `border` 描边看起开真的很奇怪
![image](https://github.com/guqing/halo-theme-higan/assets/110711363/9e414753-a4b9-4516-947f-c4bb1e58dc79)

**对比**
![image](https://github.com/guqing/halo-theme-higan/assets/110711363/a88b9eb5-b038-49b0-bb6a-5e6e861e2955)

希望博主能采纳一下

**Comment by guqing** [comment]
是有什么问题吗，你的建议没写出来

**Comment by jiancaiZhong** [comment]
还在编辑哈哈哈

**Comment by jiancaiZhong** [comment]
> 是有什么问题吗，你的建议没写出来

已经写出来了
