### ISSUE TITLE
关于页面嵌套不统一问题

### ISSUE THREAD

**Issue by jiancaiZhong** [guqing/halo-theme-higan#60]
## 我发现个别页面的页脚不是很统一

**首页页脚**
![image](https://github.com/guqing/halo-theme-higan/assets/110711363/60690244-7521-4ba2-b0f0-4734540ff6b1)

**瞬间页脚**
![image](https://github.com/guqing/halo-theme-higan/assets/110711363/83886f4c-e317-47da-aee6-70d57808b542)

## 原因

首页
![image](https://github.com/guqing/halo-theme-higan/assets/110711363/9b84f30e-f3fe-4482-9c7a-4ec7b1d55846)

瞬间
![image](https://github.com/guqing/halo-theme-higan/assets/110711363/c107668e-9664-42ac-91eb-88aba6465b51)

可以看到，在瞬间页面的页脚是被文章那个标签包裹着的

![image](https://github.com/guqing/halo-theme-higan/assets/110711363/1d653f1b-f900-4bcc-8def-95fcb157ef09)

建议将 瞬间的分页相关div 和 页脚处于同一级别

https://github.com/guqing/halo-theme-higan/assets/110711363/e3a44951-e764-4859-b9b6-c929f4f427b6

**Comment by guqing** [comment]
good catch🎈
