### ISSUE TITLE
链接无法点击

### ISSUE THREAD

**Issue by github-ado** [guqing/halo-theme-higan#67]
### 文章中的链接无法点击跳转，其他主题测试没问题
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/793a400d-2398-43c8-a9a2-3a925873cb8f)

**Comment by guqing** [comment]
如何复现呢，没发现不能点击

**Comment by github-ado** [comment]
> 如何复现呢，没发现不能点击
#### 拉到最下面~
https://ado.js.cn/archives/1702986313020

**Comment by guqing** [comment]
不能点击看起来是因为这个链接的 a 标签没有 href 属性
<img width="1475" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/ce7e93f9-f264-442c-8a3e-6eb42ea3d262">

earth 主题看起来也是一样的，所以你说的其他主题可以是哪个主题呢可能是主题做了什么处理，你使用的什么编辑器出现这个问题
<img width="1558" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/0eb70e63-d571-4dc4-9a7e-2471c737d039">

**Comment by github-ado** [comment]
文章后来重新编辑链接了，个人操作有误 @guqing

**Comment by guqing** [comment]
ok 如果没有问题我就关闭这个 issue 了
