### ISSUE TITLE
标题等级大小回显问题

### ISSUE THREAD

**Issue by adozhao** [guqing/halo-theme-higan#68]
### 编辑：
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/5d6d37e4-beac-46ac-9de2-ea1ca8dd634e)

### 主题显示效果
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/d7f9652a-617c-4754-8ce0-d88908f86c4c)

可能原作者设计如此吧...
可是最终导致的后果是，三级标题还不如文章默认字体大：/(ㄒoㄒ)/~~
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/24f59578-fac6-4c5e-ad33-bd36963d1024)

**Comment by guqing** [comment]
这确实是个问题，后续修改一下标题的大小层级 👍

感谢你对 higan 的喜欢 ❤️‍🔥，一个好的作品离不开对细节的打磨，就喜欢你这样有匠心的用户  🫡 遇到问题欢迎随时提 issue

**Comment by github-ado** [comment]
补充一下，我这个字体是在higan主题的设置中设置 **常规** 字号，导致三级标题比常规字号小。但是默认的那个小字体设置下看着比例还行，然而，小字体确实太小了，适合软妹子~

**Comment by guqing** [comment]
已重新划分了不同字体设置下的 headings 等级，近期会发版本
