### ISSUE TITLE
文章大纲的定位显示问题

### ISSUE THREAD

**Issue by adozhao** [guqing/halo-theme-higan#69]
目前大纲展开逻辑是没问题的，但是缺少定位标记显示，似乎可以改变文字颜色或者在文字下放添加粉色横线~
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/98085556-d025-4658-b7de-fb0cfffb885d)

**Comment by guqing** [comment]
good catch 👍

**Comment by HowieHz** [comment]
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/720eb3cf-b5f9-4c78-9107-135d85400ed9)
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/90323a9d-ed08-42e3-ab03-f8cd783ffe7c)

定位添加的 class 是 toc-active
但是 css 样式中是 toc-active-link
