### ISSUE TITLE
友链板

### ISSUE THREAD

**Issue by wangxiaoerYah** [guqing/halo-theme-higan#7]
真的好看，很对我味。
作者有考虑交换友链吗？

我的：[www.wangxiaoer.site](https://www.wangxiaoer.site)

**Comment by guqing** [comment]
Hi @wangxiaoerYah ，可以到博客 https://www.guqing.xyz/me/about 按格式评论，主题issue只处理主题相关的反馈或建议😛

**Comment by wangxiaoerYah** [comment]
👌
