### ISSUE TITLE
[建议] 每日一言支持自定义

### ISSUE THREAD

**Issue by adozhao** [guqing/halo-theme-higan#71]
建议新增每日一言自定义功能，哪怕只支持自定义一条也行~

![image](https://github.com/guqing/halo-theme-higan/assets/23180747/af5fe1c4-9514-49f7-ac4f-3879d6c7a8b7)

**Comment by guqing** [comment]
下面有“个人简介”如果开启一言就展示的一言不开启就使用的简介，也就是你说的这种功能
<img width="700" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/769c0894-b108-4809-8ca9-6062c4eb0d3b">

**Comment by adozhao** [comment]
> 下面有“个人简介”如果开启一言就展示的一言不开启就使用的简介，也就是你说的这种功能 <img alt="image" width="700" src="https://private-user-images.githubusercontent.com/38999863/296167124-769c0894-b108-4809-8ca9-6062c4eb0d3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTEzNjYsIm5iZiI6MTcwNTA1MTA2NiwicGF0aCI6Ii8zODk5OTg2My8yOTYxNjcxMjQtNzY5YzA4OTQtYjEwOC00ODA5LThjYTktNjA2MmM0ZWIwZDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA5MTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NGMxM2YwYmRhZjkxNTM0YjRhMjMxMjE2OWFkMmJjZThkMTc0YjRlZThlM2EzOTJlMjllY2Q1ODU4MzY0OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxuDf6OV0wuoYygdQx3njhuW6GiXuah1RaqQed_NiY4">

666啊，学些了~

**Comment by guqing** [comment]
> 666啊，才看到有简介~而且这个位置还可以巧妙的作为”站点公告“，哇，无穷想象

🤣

**Comment by adozhao** [comment]
你这个头像35K，每次都能看到加载~
![image](https://github.com/guqing/halo-theme-higan/assets/23180747/68c09c58-0646-46ae-a58d-5ae62bf83cf0)

**Comment by guqing** [comment]
你这个是哪里的

**Comment by adozhao** [comment]
> 你这个是哪里的

你可以进来看看， ”友链“ ado.zone

**Comment by guqing** [comment]
确实有点慢，服务器在新加坡国内访问是这样, io 域名不能备案
