### ISSUE TITLE
行内代码块渲染失败

### ISSUE THREAD

**Issue by Erzbir** [guqing/halo-theme-higan#73]
升级到 2.7.1 后, 行内代码块不渲染

**Comment by guqing** [comment]
所说的是这种吗 inline quote，如果是这个可以试试下载最新的 main 分支安装并使用无痕模式打开，我记得修了可能忘记发版本了
<img width="424" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/bc6d5ed2-1a5c-4c8c-81b9-b5d03e730eb5">

**Comment by Erzbir** [comment]
> 所说的是这种吗 inline quote，如果是这个可以试试下载最新的 main 分支安装并使用无痕模式打开，我记得修了可能忘记发版本了
> 
> 

2.6.0 没有问题，之后的版本都有问题

**Comment by guqing** [comment]
> > 所说的是这种吗 inline quote，如果是这个可以试试下载最新的 main 分支安装并使用无痕模式打开，我记得修了可能忘记发版本了
> 
> 2.6.0 没有问题，之后的版本都有问题

确实，感谢提出这个问题，稍后我会修复
