### ISSUE TITLE
文章渲染有问题，文本不能靠左对齐

### ISSUE THREAD

**Issue by HowieHz** [guqing/halo-theme-higan#77]
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/5afef5fb-a3e3-4e87-b627-ab4ec84389d9)
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/a8298eb3-5119-4149-a4bf-7b286950f064)

**Comment by guqing** [comment]
感谢提出此问题，我会优化一下

**Comment by guqing** [comment]
已在 Main 分支修复，等待发版
