### ISSUE TITLE
关于全局搜索功能

### ISSUE THREAD

**Issue by yunCrush** [guqing/halo-theme-higan#8]
请问目前没有发现可以支持全局搜索的功能，后面会添加这个功能吗？

**Comment by guqing** [comment]
将在 Halo 2.0 发布 beta 版后为此主题提供全局搜索功能，目前此主题 1.x 版本不会再提供，适用于 Halo 2.0 的主题版本也快迁移完成 [halo-theme-higan next](https://github.com/guqing/halo-theme-higan/tree/feature/next)
Halo 2.0 的全局搜索目前正在进行中，可以关注此 Issue https://github.com/halo-dev/halo/issues/2637 相关的 PR

**Comment by ruibaby** [comment]
2.0.0 Beta.1 已经支持全文搜索，https://github.com/halo-dev/halo/releases/tag/v2.0.0-beta.1

主题端适配可参考：https://github.com/halo-dev/halo/discussions/2696#discussioncomment-4119049

**Comment by guqing** [comment]
已在 [v2.0.0-alpha.2[(https://github.com/guqing/halo-theme-higan/releases/tag/v2.0.0-alpha.2) 版本支持
