### ISSUE TITLE
已安装 lightgallery.js 灯箱，无法放大图像

### ISSUE THREAD

**Issue by jalr4ever** [guqing/halo-theme-higan#82]
# 问题

现场：https://jalr4ever.cn/archives/gong-cheng-jing-yan---fu-wu-jian-ren-zheng-fang-an

# 版本

- halo-theme-higan: 2.8.0
- halo: 2.12.2
- lightgallery.js 灯箱 1.1.1

**Comment by guqing** [comment]
参考如下配置来配置一下 lightgallery 插件试试呢

<img width="797" alt="image" src="https://github.com/guqing/halo-theme-higan/assets/38999863/7e41df3e-d973-4043-9a08-a11e17d2b0ed">

**Comment by jalr4ever** [comment]
> 参考如下配置来配置一下 lightgallery 插件试试呢
> 
> <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/38999863/311930419-7e41df3e-d973-4043-9a08-a11e17d2b0ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjI4NTgsIm5iZiI6MTcxMDIyMjU1OCwicGF0aCI6Ii8zODk5OTg2My8zMTE5MzA0MTktN2U0MWRmM2UtZDk3My00MDQzLTlhMDgtYTExZTE3ZDJiMGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA1NDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzY2RmY2U1OGM4ZTI1MWQyNjJiNDI4NmQ0YzhhNTcwZTI1MmM2NzY0YTBiNjI0MTQ4ZDlhMGMzZDkyODcwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.omOYOlLd29eJ5-rGTOtyX3KiBThiFRHFnh5qXAmKJ2c">

感谢回复！可以了。不过看着这个插件有点弱啊，因为点开来后，图片缩放反而更小了... 没有个放大、缩小的按钮之类的么 🥹

![image](https://github.com/guqing/halo-theme-higan/assets/23929139/597b7519-8eb3-4158-8707-1476a7fa6626)

**Comment by guqing** [comment]
> 感谢回复！可以了。不过看着这个插件有点弱啊，因为点开来后，图片缩放反而更小了... 没有个放大、缩小的按钮之类的么 🥹

给这个 lightgallery 插件提 issue 😀

**Comment by jalr4ever** [comment]
> > 感谢回复！可以了。不过看着这个插件有点弱啊，因为点开来后，图片缩放反而更小了... 没有个放大、缩小的按钮之类的么 🥹
> 
> 给这个 lightgallery 插件提 issue 😀

已建立：https://github.com/halo-sigs/plugin-lightgallery/issues/16

**Comment by HowieHz** [comment]
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/2dfaefab-cdd7-4a79-8331-bfbf1ddac2b6)

`/moments`的匹配改为`.medium`可能好点，不然的话会把发布者的头像也加到浏览列表里
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/eefc097c-e0c1-454e-a004-c0473519be58)

**Comment by HowieHz** [comment]
另外`/moments`也要改成`/moments/**`
否则翻到第二页就失效了`url/moments/page/2`
