### ISSUE TITLE
补充缺失的aria-label属性

### ISSUE THREAD

**Issue by HowieHz** [guqing/halo-theme-higan#83]
跑lighthouse报表发现的
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/17f3e47f-10e8-4373-b5c1-49b2cf01f79b)
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/50e7cb16-ec19-430e-b9c2-198faa668f64)
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/d72a5483-1851-4217-98bd-01100f3b5a64)
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/aadde74e-fe65-47aa-9523-7ced6aaaeb0e)

**Comment by guqing** [comment]
感谢反馈,后续会为这些 a 标签添加 aria-label 以提高可访问性
