### ISSUE TITLE
分类中的文章日期问题

### ISSUE THREAD

**Issue by jalr4ever** [guqing/halo-theme-higan#84]
现场：https://jalr4ever.cn/categories/workingthings

问题：为何看到的日期都是一样的，是设计如此么？期望中应该是按照文章发布时间的日期？

![image](https://github.com/guqing/halo-theme-higan/assets/23929139/2d95ee74-07a8-437e-a3b8-c673aa147df4)

**Comment by guqing** [comment]
感谢反馈,这里显示的是创建时间,确实应该改为发布时间比较合适

**Comment by jalr4ever** [comment]
Hi, 这个 bug 有进展不，啥时候会发下一个版本呀？

**Comment by HowieHz** [comment]
> Hi, 这个 bug 有进展不，啥时候会发下一个版本呀？

![image](https://github.com/guqing/halo-theme-higan/assets/94725606/f6ddc3e3-a055-4ab4-a3bd-204284245526)
https://github.com/HowieHz/halo-theme-higan/tree/fix-%2384

试试好使不，直接 Download ZIP，然后导入覆盖原主题
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/ccb25bcf-2330-4a88-b35b-9d18499e0dd4)

**Comment by jalr4ever** [comment]
> > Hi, 这个 bug 有进展不，啥时候会发下一个版本呀？
> 
> ![image](https://private-user-images.githubusercontent.com/94725606/328328422-f6ddc3e3-a055-4ab4-a3bd-204284245526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDg2MjcsIm5iZiI6MTcxNTA0ODMyNywicGF0aCI6Ii85NDcyNTYwNi8zMjgzMjg0MjItZjZkZGMzZTMtYTA1NS00YWI0LWEzYmQtMjA0Mjg0MjQ1NTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAyMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OWE2NmE3YzEwMDI2MjJjNjk5ZTZhYTRmOGYwYzRhZTBhZjMxZTcwMjYxNDY4ZGY3ZmEwMzBiNmIwYzJhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyImQnsfn0JnZl_TeddAkYOfGHChqY-kMjAeQvfy3ok) https://github.com/HowieHz/halo-theme-higan/tree/fix-%2384
> 
> 试试好使不，直接 Download ZIP，然后导入覆盖原主题 ![image](https://private-user-images.githubusercontent.com/94725606/328328926-ccb25bcf-2330-4a88-b35b-9d18499e0dd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDg2MjcsIm5iZiI6MTcxNTA0ODMyNywicGF0aCI6Ii85NDcyNTYwNi8zMjgzMjg5MjYtY2NiMjViY2YtMjMzMC00YTg4LWIzNWItOWQxODQ5OWUwZGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAyMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYWVhODk3YWQwY2I4ZjJlYWZiODM4MjJjYTc4MDQ1ZDk0N2UxYWFmMDNjMWRjNWY1ZDI5MTkwMDUwZmEyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KqzjlkpaSokTkOso46vQaNi1WuLfO2wJH4-J2ZqbMho)
> 
> 显示的应该是这里的发布日期了 ![image](https://private-user-images.githubusercontent.com/94725606/328329307-21053f8b-c105-4b0a-a35c-7be51d4326a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDg2MjcsIm5iZiI6MTcxNTA0ODMyNywicGF0aCI6Ii85NDcyNTYwNi8zMjgzMjkzMDctMjEwNTNmOGItYzEwNS00YjBhLWEzNWMtN2JlNTFkNDMyNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAyMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNjNlYzFmZjIzNmQ1ODNmMTlkMjgyZjhjZjEwYzdkNzA0YjJiMDA3YzUxNGRjNDJlZDU2Mjc1ODM5MTg4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2cqVNLT9tO0hTphiTZCiGXMyzaDRxkLgakMchIidmY)

成功了， @guqing 快上线合并小哥的 PR 吧 😄

**Comment by guqing** [comment]
> > > Hi, 这个 bug 有进展不，啥时候会发下一个版本呀？
> 成功了， @guqing 快上线合并小哥的 PR 吧 😄

好了，我尽快发版🤠
