### ISSUE TITLE
优化移动端footer显示

### ISSUE THREAD

**Issue by HowieHz** [guqing/halo-theme-higan#87]
桌面端显示的效果：
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/0c0aed28-99ee-482d-8758-869278339553)

移动端显示的效果：
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/66297bff-71eb-4f98-b02f-a427301bc237)

可能更理想的移动端显示效果：
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/246bdfb1-7306-470f-8be3-eae46e717b2f)

**Comment by guqing** [comment]
good idea 🎈
