### ISSUE TITLE
一些样式优化，仅代表个人意见。

### ISSUE THREAD

**Issue by xbs9666** [guqing/halo-theme-higan#88]
-  能否将头像高度设置为header的高度，这样可以保持一致，或者让头像居中。

![logo](https://github.com/guqing/halo-theme-higan/assets/29635573/adcd60f6-30d6-4fcd-8252-af405c0bf625)

- 归档年份之间的空白 
![归档-flex-auto](https://github.com/guqing/halo-theme-higan/assets/29635573/af9fb4dc-2a01-47a2-ac9b-589a4885dc21)
![归档](https://github.com/guqing/halo-theme-higan/assets/29635573/00f71173-438b-4bd2-9a3a-e22150f169ba)
![年份差距大](https://github.com/guqing/halo-theme-higan/assets/29635573/39069025-afd2-43e1-a94d-9f7b49012be7)
当年份是连续时样式看起来还可以，但感觉还是有点大，删了flex-auto的类会更好点。
当年份中间有空缺时，中间间隔太大，看起来怪怪的。

**Comment by xbs9666** [comment]
https://xiaolangjun.top/
我这边归档内看起来比较明显些， @HowieHz

**Comment by HowieHz** [comment]
> https://xiaolangjun.top/ 我这边归档内看起来比较明显些， @HowieHz

测试出来了这个的触发条件是要把页脚的代码输入清空（设置-代码注入-页脚）

原始：
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/1361b4f5-e098-4e0c-8b36-b50939c35c38)
删除footer-left：
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/56d25ae3-5c21-4058-a020-39e5f54f04ae)
让年份比较多, 文章比较少：
![image](https://github.com/guqing/halo-theme-higan/assets/94725606/1a1bbcf4-d0e4-4a71-a4f4-e95aef2689f0)

**Comment by guqing** [comment]
> [xiaolangjun.top](https://xiaolangjun.top/) 我这边归档内看起来比较明显些， @HowieHz

这确实是个问题，后续我优化一下，之前没有发现，应该是因为之前想让只有很少数据的时候分页不会往上跑能占满剩余高度然后没注意整出来的问题

**Comment by xbs9666** [comment]
> > https://xiaolangjun.top/ 我这边归档内看起来比较明显些， @HowieHz
> 
> 测试出来了这个的触发条件是要把页脚的代码注入清空（设置-代码注入-页脚）
> 
> 原始： ![image](https://private-user-images.githubusercontent.com/94725606/318290027-1361b4f5-e098-4e0c-8b36-b50939c35c38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDExNzEsIm5iZiI6MTcxMTk0MDg3MSwicGF0aCI6Ii85NDcyNTYwNi8zMTgyOTAwMjctMTM2MWI0ZjUtZTA5OC00ZTBjLThiMzYtYjUwOTM5YzM1YzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZDc0NzY5ZDBjOTdmYWI0OTBhNTM2ZTRhMmU4ZTI2ODlkYzk4YzJjNjRiZWMxNGVmYjE4MTU4Zjg3ZGJjNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c1x7DJbS6IBL_O9tjJsLpkcmcY_hgoMYBSb7DvfeTr0) 删除footer-left： ![image](https://private-user-images.githubusercontent.com/94725606/318290051-56d25ae3-5c21-4058-a020-39e5f54f04ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDExNzEsIm5iZiI6MTcxMTk0MDg3MSwicGF0aCI6Ii85NDcyNTYwNi8zMTgyOTAwNTEtNTZkMjVhZTMtNWMyMS00MDU4LWEwMjAtMzllNWY1NGYwNGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNDlhNGI4MjI3Mzc1MmIwOTllMWRiOGNmYzFhN2NmOTg5OWY5YWI5NDdhZjc0ZDUxOTg1NGIwMzFlNDI3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oT_onrWBMGYog4t5bxkcYWa6rj_M6rkSffprSVQ8bQI) 让年份比较多, 文章比较少： ![image](https://private-user-images.githubusercontent.com/94725606/318290073-1a1bbcf4-d0e4-4a71-a4f4-e95aef2689f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDExNzEsIm5iZiI6MTcxMTk0MDg3MSwicGF0aCI6Ii85NDcyNTYwNi8zMTgyOTAwNzMtMWExYmJjZjQtZDBlNC00YTcxLWE0ZjQtZTk1YWVmMjY4OWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDBjMTA0YWU1MzNjZDZjNGZhYmE3MWEzMmE5ZmRjNDViODlhYjg0MzI4MDU4NmY4MTJmYjY4NmFmNjNhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JO-Ys8h4ZWCWE6dyOTLMEyByIwPnA0C5ntAuVnS-Ei0)
> 
> 暂时可以先往页脚随便注入点文字来解决这个问题

好的感谢
