### ISSUE TITLE
如何去除RSS

### ISSUE THREAD

**Issue by GD2021** [guqing/halo-theme-higan#96]
![image](https://github.com/guqing/halo-theme-higan/assets/81171294/1e56b015-abe7-4b05-9202-6cc8a4752cdc)

RSS链接我关掉了，请问如何去除这个标识，难看。

**Comment by guqing** [comment]
我后续将加一个判断，如果没有任何联系方式则将不现实这个文字，临时解决办法：
在`系统设置->全局代码注入->全局 Head 标签` 中加入以下内容:
```html
<style>
  div.max-width.mx-auto.px3.ltr > div > p {
    display:none;
  }
</style>
```
